const colors = {
  grey900: '#18181B',
  almostBlack: '#18181B',
  grey800: '#27272A',
  lightBlack: '#27272A',
  grey700: '#3F3F46',
  grey600: '#52525B',
  almostWhite: '#E6E6E6',
  white: '#f4f4f5',
  white10: 'rgba(255, 255, 255, 0.1)',
  white30: 'rgba(255, 255, 255, 0.3)',
  black: '#000',
  black10: 'rgba(0, 0, 0, 0.1)',
  primary: '#1AB6FF',
  greyLight: '#F4F7FA',
  grey: '#E8EBED',
  greyMid: '#C5CCD3',
  greyDark: '#DAE1E9',
};

export const base = {
  ...colors,
  fontFamily:
    "Lato, -apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Oxygen, Ubuntu,Cantarell,'Open Sans','Helvetica Neue',sans-serif",
  fontFamilyMono: "'SFMono-Regular',Consolas,'Liberation Mono', Menlo, Courier,monospace",
  fontWeight: 400,
  zIndex: 100,
  link: colors.primary,
  placeholder: '#B1BECC',
  textSecondary: '#4E5C6E',
  textLight: colors.white,
  textHighlight: '#b3e7ff',
  textHighlightForeground: colors.black,
  selected: colors.primary,
  codeComment: '#6a737d',
  codePunctuation: '#5e6687',
  codeNumber: '#d73a49',
  codeProperty: '#c08b30',
  codeTag: '#3d8fd1',
  codeString: '#032f62',
  codeSelector: '#6679cc',
  codeAttr: '#c76b29',
  codeEntity: '#22a2c9',
  codeKeyword: '#d73a49',
  codeFunction: '#6f42c1',
  codeStatement: '#22a2c9',
  codePlaceholder: '#3d8fd1',
  codeInserted: '#202746',
  codeImportant: '#c94922',

  blockToolbarBackground: colors.white,
  blockToolbarTrigger: colors.greyMid,
  blockToolbarTriggerIcon: colors.white,
  blockToolbarItem: colors.grey800,
  blockToolbarText: colors.grey800,
  blockToolbarHoverBackground: colors.greyLight,
  blockToolbarDivider: colors.greyMid,

  noticeInfoBackground: '#F5BE31',
  noticeInfoText: colors.grey800,
  noticeTipBackground: '#9E5CF7',
  noticeTipText: colors.white,
  noticeWarningBackground: '#FF5C80',
  noticeWarningText: colors.white,
};

export const light = {
  ...base,
  background: colors.white,
  text: colors.grey800,
  code: colors.grey700,
  cursor: colors.black,
  divider: colors.greyMid,

  toolbarBackground: colors.grey700,
  toolbarHoverBackground: colors.black,
  toolbarInput: colors.white10,
  toolbarItem: colors.white,

  tableDivider: colors.greyMid,
  tableSelected: colors.primary,
  tableSelectedBackground: '#E5F7FF',

  quote: colors.greyDark,
  codeBackground: colors.greyLight,
  codeBorder: colors.grey,
  horizontalRule: colors.greyMid,
  imageErrorBackground: colors.greyLight,

  scrollbarBackground: colors.greyLight,
  scrollbarThumb: colors.greyMid,
};

export const dark = {
  ...base,
  background: colors.grey800,
  text: colors.almostWhite,
  textSecondary: colors.white30,
  textHighlightForeground: colors.almostWhite,
  code: colors.almostWhite,
  cursor: colors.white,
  divider: colors.white30,
  placeholder: colors.white30,

  toolbarBackground: colors.grey900,
  toolbarHoverBackground: colors.grey700,
  toolbarInput: colors.white30,
  toolbarItem: colors.almostWhite,

  blockToolbarBackground: colors.grey800,
  blockToolbarTrigger: colors.grey700,
  blockToolbarTriggerIcon: colors.white,
  blockToolbarItem: colors.grey900,
  blockToolbarText: colors.almostWhite,
  blockToolbarHoverBackground: colors.grey900,
  blockToolbarDivider: colors.grey700,

  tableDivider: colors.grey700,
  tableSelected: colors.primary,
  tableSelectedBackground: '#002333',

  quote: colors.greyDark,
  codeBackground: colors.black,
  codeBorder: colors.grey700,
  codeString: '#3d8fd1',
  horizontalRule: colors.grey700,
  imageErrorBackground: 'rgba(0, 0, 0, 0.5)',

  scrollbarBackground: colors.black,
  scrollbarThumb: colors.grey700,
};

export default dark;
